name: Testing and Coverage

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Testing:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, "3.10", 3.11-dev]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run Tests
        run: |
          pip install -e .[tests]
          pytest -v .
